style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/ik-workshop/workshop-
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
